// Original screenplay commissions (Phase 4). The player pays a specific writer
// to write a brand-new original in a chosen genre - the inverse of the authored
// Opportunity Market (there the market picks the writer; here the player does).
// The screenplay is generated by the same Phase 2 author-biased generator, so
// its identity reflects the commissioned writer; it's a premium, directed
// alternative to gambling cheaply on whatever the market happens to post.
import type { Asset, DevelopmentEvent, GameDay, Genre, Money, PendingCommission, Person, Script } from '../types';
import { generateScriptOptions } from './scriptGenerator';
import { writerProfileFromPerson } from './writers';
import type { RandomFn } from './random';

// A full original screenplay is a premium engagement - roughly a writer's whole
// typical fee, so commissioning an elite is genuinely dear (and directed), the
// opposite end of the trade from acquiring a cheap Studio-Original opportunity.
const COMMISSION_FEE_MULTIPLIER = 1;

export function commissionFee(writerTypicalSalary: Money): Money {
  return Math.round(writerTypicalSalary * COMMISSION_FEE_MULTIPLIER);
}

// Writing from scratch takes longer than reworking an existing draft - a base
// plus a complexity term off the delivered script.
const DURATION_BASE = 42;
const DURATION_COMPLEXITY = 14;

export function commissionDurationDays(script: Script): number {
  return DURATION_BASE + Math.round((script.complexity / 100) * DURATION_COMPLEXITY);
}

/** The duration a commission can take, for the pre-commission estimate shown before the script (and so its complexity) is known. */
export function commissionDurationBounds(): { min: number; max: number } {
  return { min: DURATION_BASE, max: DURATION_BASE + DURATION_COMPLEXITY };
}

/**
 * Rolls the commissioned screenplay via the Phase 2 author-biased generator with
 * the player's chosen writer and genre - the same call engine/opportunities.ts
 * makes, minus the market's writer/genre selection (the player made both).
 * Null if the person has no writer career (guarded before this in the reducer).
 */
export function generateCommissionedScript(writer: Person, genre: Genre, rng: RandomFn): Script | null {
  const profile = writerProfileFromPerson(writer);
  if (!profile) return null;
  return generateScriptOptions(genre, rng, 1, profile)[0];
}

/** The founding development event of a commissioned Asset. */
export function commissionedEvent(day: GameDay, writerName: string, fee: Money): DevelopmentEvent {
  return { day, kind: 'commissioned', summary: `Original screenplay commissioned from ${writerName}`, costDelta: -fee };
}

/** Assembles the pending-commission record - the reducer's single source for the shape. `id` doubles as the delivered Asset's id (the script id is globally unique - Phase 1). */
export function makePendingCommission(writer: Person, genre: Genre, startedOnDay: GameDay, readyOnDay: GameDay, script: Script, fee: Money): PendingCommission {
  return { id: `commission-${script.id}`, writerId: writer.id, writerName: writer.identity.name, genre, startedOnDay, readyOnDay, script, fee };
}

export interface CommissionSettlementResult {
  /** New owned Assets to append - commissions that have been delivered by `totalDays`. */
  delivered: Asset[];
  /** Commissions still in flight. */
  pendingCommissions: PendingCommission[];
}

/**
 * Delivers every commission whose readyOnDay has arrived - wrapping its
 * already-generated script as a new owned Asset (source 'Studio Original',
 * acquisitionCost = the fee already paid, credited to the writer) - and leaves
 * the rest in flight. The delivered Asset is indistinguishable downstream from
 * an acquired one, so the "script cost is charged once, at acquisition"
 * invariant holds (here the fee is the acquisition). The writer's own commitment
 * expires by its endDay, so no talent-pool write-back is needed here.
 */
export function settlePendingCommissions(pending: PendingCommission[], totalDays: GameDay): CommissionSettlementResult {
  const delivered: Asset[] = [];
  const stillPending: PendingCommission[] = [];
  for (const commission of pending) {
    if (totalDays < commission.readyOnDay) {
      stillPending.push(commission);
      continue;
    }
    delivered.push({
      id: commission.id,
      script: commission.script,
      source: 'Studio Original',
      acquisitionCost: commission.fee,
      acquiredOnDay: commission.readyOnDay,
      writerIds: [commission.writerId],
      developmentHistory: [commissionedEvent(commission.readyOnDay, commission.writerName, commission.fee)],
    });
  }
  return { delivered, pendingCommissions: stillPending };
}
