// @vitest-environment jsdom
//
// Found during a quality review of the checkbox-filter commits (Opportunity
// Market / Release Calendar): OpportunityMarket.tsx seeded its "selected
// sources" set once at mount, via useState(() => new Set(sourceOptions...)),
// so a source type that appeared later (e.g. a new opportunity batch
// generated by the background day-tick while the screen stayed open) was
// silently excluded from the filtered results by default. ReleaseCalendar.tsx
// had a reconciliation useEffect for the same problem, with a comment
// claiming to "include newly appearing studios and genres automatically" -
// but the implementation only ever filtered stale ids out, never added new
// ones in, so the same bug existed there too despite the comment. This hook
// replaces both bespoke implementations with one correct, tested one.
import { describe, it, expect } from 'vitest';
import { renderHook, act } from '@testing-library/react';
import { useReconciledFilterSelection } from './useReconciledFilterSelection';

describe('useReconciledFilterSelection', () => {
  it('starts with every option selected', () => {
    const { result } = renderHook(() => useReconciledFilterSelection(['a', 'b', 'c']));
    expect(result.current[0]).toEqual(new Set(['a', 'b', 'c']));
  });

  it('a genuinely new option is automatically selected, not left out', () => {
    const { result, rerender } = renderHook(({ optionIds }) => useReconciledFilterSelection(optionIds), {
      initialProps: { optionIds: ['a', 'b'] },
    });
    expect(result.current[0]).toEqual(new Set(['a', 'b']));

    rerender({ optionIds: ['a', 'b', 'c'] });
    expect(result.current[0]).toEqual(new Set(['a', 'b', 'c']));
  });

  it('an option the player deliberately deselected stays deselected when unrelated options change', () => {
    const { result, rerender } = renderHook(({ optionIds }) => useReconciledFilterSelection(optionIds), {
      initialProps: { optionIds: ['a', 'b', 'c'] },
    });

    act(() => {
      result.current[1](new Set(['a', 'c'])); // player unchecked 'b'
    });
    expect(result.current[0]).toEqual(new Set(['a', 'c']));

    // A genuinely new option 'd' appears - 'b' must not silently come back.
    rerender({ optionIds: ['a', 'b', 'c', 'd'] });
    expect(result.current[0]).toEqual(new Set(['a', 'c', 'd']));
  });

  it('an option that disappears is dropped from the selection', () => {
    const { result, rerender } = renderHook(({ optionIds }) => useReconciledFilterSelection(optionIds), {
      initialProps: { optionIds: ['a', 'b', 'c'] },
    });

    rerender({ optionIds: ['a', 'c'] });
    expect(result.current[0]).toEqual(new Set(['a', 'c']));
  });

  it('a real-world case: filter set is empty at mount, then options arrive later - all arrive selected', () => {
    const { result, rerender } = renderHook(({ optionIds }) => useReconciledFilterSelection(optionIds), {
      initialProps: { optionIds: [] as string[] },
    });
    expect(result.current[0]).toEqual(new Set());

    rerender({ optionIds: ['Spec Screenplay', 'Studio Original'] });
    expect(result.current[0]).toEqual(new Set(['Spec Screenplay', 'Studio Original']));
  });
});
