import { useEffect, useRef, useState } from 'react';

/**
 * A Set<string> filter selection that starts fully-selected and then keeps
 * itself reconciled against `optionIds` as it changes: options that
 * disappear are dropped, options that are genuinely new (weren't present
 * the last time this ran) are added automatically, and anything the
 * caller has deliberately deselected stays deselected. "Everything
 * selected" is meant to be the persistent default for options the player
 * hasn't touched, not a one-time snapshot of whatever existed at mount -
 * a plain `useState(() => new Set(optionIds))` only ever reflects that
 * first render, so a genuinely new option appearing later (e.g. a new
 * opportunity source generated by the background day-tick while this
 * screen is open) would silently read as "deselected" even though the
 * player never touched it.
 */
export function useReconciledFilterSelection(optionIds: string[]): [Set<string>, (next: Set<string>) => void] {
  const [selected, setSelected] = useState<Set<string>>(() => new Set(optionIds));
  const knownIdsRef = useRef<Set<string>>(new Set(optionIds));

  useEffect(() => {
    const previouslyKnown = knownIdsRef.current;
    const newlyAppeared = optionIds.filter((id) => !previouslyKnown.has(id));
    const currentIds = new Set(optionIds);
    const anyRemoved = [...previouslyKnown].some((id) => !currentIds.has(id));
    if (newlyAppeared.length === 0 && !anyRemoved) return;

    knownIdsRef.current = currentIds;
    setSelected((current) => new Set([...current].filter((id) => currentIds.has(id)).concat(newlyAppeared)));
  }, [optionIds]);

  return [selected, setSelected];
}
